formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"


formats:
   - pdf
   - epub

python:
  version: "3.7"
  pip_install: true
  install:
    - requirements: docs/requirements.txt
  extra_requirements:
    - docs
